# Generated by Django 5.0.1 on 2024-01-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('institution_image', models.ImageField(blank=True, null=True, upload_to='institution_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=255)),
                ('date_received', models.DateField()),
                ('validity', models.BooleanField(default=True)),
                ('institution_emitted', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('certificate_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('technologies_used', models.JSONField(default=list)),
                ('achievements', models.TextField()),
                ('job_description', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('published_related_work', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField()),
                ('github_link', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('demo_link', models.URLField()),
                ('technologies_used', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_owner', models.CharField(max_length=255)),
                ('presentation_header', models.CharField(max_length=255)),
                ('about_me', models.TextField()),
                ('credits', models.TextField()),
                ('academic_history', models.ManyToManyField(to='homepage.academichistory')),
                ('certificates', models.ManyToManyField(to='homepage.certificate')),
                ('professional_experience', models.ManyToManyField(to='homepage.professionalexperience')),
                ('projects_built', models.ManyToManyField(to='homepage.project')),
            ],
            options={
                'verbose_name': 'Portfolio Site',
                'verbose_name_plural': 'Portfolio Site',
            },
        ),
    ]
