# Generated by Django 5.0.1 on 2024-01-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_portfoliosite_academic_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academichistory',
            options={'verbose_name': 'Academic History', 'verbose_name_plural': 'Academic History'},
        ),
    ]
